In [0]:
#importing all the required packages
import numpy as np
import pandas as pd
import nltk as nltk
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
import statistics as s
from sklearn.metrics import confusion_matrix 

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
#importing dataset that is preprocessed
df=pd.read_csv('/content/drive/My Drive/AIt/job_text.csv')

In [0]:
df.head()

Unnamed: 0                                           job_text  fraudulent
0           0  food52 a fast grow jame beard award win onlin ...           0
1           1  organis focus vibrant awesom ! do you have a p...           0
2           2  our client locat in houston is activ seek an e...           0
3           3  the compani esri environment system research i...           0
4           4  job titl item review managerloc fort worth tx ...           0

In [0]:
#Dropping the Un-named column
df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)

In [0]:
#Preparing the data for train test split
x=df.drop(['fraudulent'],axis=1)
y=df['fraudulent']

In [0]:
#splitting the data into train and test set
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [0]:
#reset the custom index generated during train, test split
X_train.reset_index(drop=True,inplace=True)

In [0]:
#reset the custom index generated during train, test split
y_train.reset_index(drop=True,inplace=True)

In [0]:
#Doing K fold Cross Validation on the training set. We use 5 folds so n_splits=5
folds = StratifiedKFold(n_splits=5, random_state=0)
i=0
#create a list for storing accuracy reports and scores
acc_report=[]
acc_score=[]
for train, test in folds.split(X_train, y_train):
    print(train)
    print(test)
    #taking only text data from training data into another variable to perform TF-idf vectorization
    x_train1, x_test1 = X_train['job_text'][train], X_train['job_text'][test]
    #taking the test data into another variable 
    y_train1, y_test1 = y_train[train], y_train[test]
    i=i+1
    
    #Using TF-IDF vectorizer to generate a TF-IDF matrix with ngram range (1,2)
    tfidf = TfidfVectorizer(stop_words="english",ngram_range=(1,2))
    x_train1 = tfidf.fit_transform(x_train1)
    print(x_train1.shape)
    x_test1 = tfidf.transform(x_test1)
    print("tfidf"+str(i))
    
    #Perform Naive Bayes classification to make predictions on the train data and check how model works on our dataset.
    clf = MultinomialNB(alpha=1.0)
    clf.fit(x_train1, y_train1)
    y_pred = clf.predict(x_test1)
    scores = accuracy_score(y_test1, y_pred)
    report=classification_report(y_test1, y_pred)
    #use append() to store all the 5 reports and scores in the created list
    acc_report.append(report)
    acc_score.append(scores)
    print(scores)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


[ 2854  2855  2856 ... 14300 14301 14302]
[   0    1    2 ... 2942 3005 3035]
(11442, 594778)
tfidf1
0.952464173365956
[    0     1     2 ... 14300 14301 14302]
[2854 2855 2856 ... 5921 5978 5982]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(11442, 593941)
tfidf2
0.952464173365956
[    0     1     2 ... 14300 14301 14302]
[5704 5705 5706 ... 8582 8583 8584]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(11442, 593348)
tfidf3
0.952464173365956
[    0     1     2 ... 14300 14301 14302]
[ 8523  8527  8585 ... 11512 11517 11527]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(11443, 594379)
tfidf4
0.9527972027972028
[    0     1     2 ... 11512 11517 11527]
[11438 11439 11440 ... 14300 14301 14302]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(11443, 591920)
tfidf5
0.9524475524475524


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [0]:
#mean of validation score
print(s.mean(acc_score))

0.9525274550685247


In [0]:
#Now using TF-IDF vectorizer to generate TF-IDF matrix for both X_train and x_test with ngram range (1,2)
tfidf = TfidfVectorizer(stop_words="english",ngram_range=(1,2))
x_train=tfidf.fit_transform(X_train['job_text'])
x_test=tfidf.transform(X_test['job_text'])

In [0]:
# check the shape of train and test data
x_train.shape
x_test.shape

(3576, 680921)

In [0]:
X_train.head()

job_text
0  the state of the art in big data is simpl thin...
1  base in new york citi sumal is a connect data ...
2  we have more than 1500 job open in our websit ...
3  the right candid will be an integr part of our...
4  you will be respons for work directli with a s...

In [0]:
#using Naive Bayes with smoothing factor value as 1 and make predictions on test data
clf = MultinomialNB(alpha=1.0)
clf.fit(x_train, y_train)
pred = clf.predict(x_test)
scores = accuracy_score(y_test, pred)
report=classification_report(y_test, pred)
print("Naive Bayes results:")
print("Accuracy:","\n",scores)
print("Accuracy report:","\n",report)
print("Confusion Matrix:","\n",confusion_matrix(y_test, pred))

Naive Bayes results:
Accuracy: 
 0.947986577181208
Accuracy report: 
               precision    recall  f1-score   support

           0       0.95      1.00      0.97      3390
           1       0.00      0.00      0.00       186

    accuracy                           0.95      3576
   macro avg       0.47      0.50      0.49      3576
weighted avg       0.90      0.95      0.92      3576

Confusion Matrix: 
 [[3390    0]
 [ 186    0]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [0]:
#Using Logistic Regression with default parameters to make predictions on test data
classifier = LogisticRegression()
classifier.fit(x_train , y_train)
prediction=classifier.predict(x_test)
model_score = accuracy_score(y_test, prediction)
class_report=classification_report(y_test, prediction)
print("Logistic Regression results:")
print("Accuracy:","\n",model_score)
print("Accuracy report:","\n",class_report)
print("Confusion Matrix:","\n",confusion_matrix(y_test, prediction))

Logistic Regression results:
Accuracy: 
 0.9611297539149888
Accuracy report: 
               precision    recall  f1-score   support

           0       0.96      1.00      0.98      3390
           1       1.00      0.25      0.40       186

    accuracy                           0.96      3576
   macro avg       0.98      0.63      0.69      3576
weighted avg       0.96      0.96      0.95      3576

Confusion Matrix: 
 [[3390    0]
 [ 139   47]]
